project:
  type: website

website:
  title: "Products of Procrastination"
  site-url: https://owenjonesuob.github.io
  description: "I'm a data scientist/engineer living in Cardiff, United Kingdom. This is a collection of projects I have spent time on while I was supposed to be doing other things."
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/owenjonesuob
      - icon: rss
        href: index.xml
  page-footer: |
    <img src="/neuronsbanner.png">
    <br>
    <span>Copyright &#169; 2024 <a href="https://owenjonesuob.github.io/">Owen Jones</a></span>
  favicon: favicon.png
  twitter-card:
    creator: "@owenjonesuob"
  google-analytics: "UA-91389971-1"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css

execute:
  freeze: auto
